name: SignWarp
api: 2.1.0
version: 2.0.0
load: POSTWORLD
main: aliuly\signwarp\Main
author: aliuly
softdepend: [WorldProtect]
website: https://github.com/Muirfield/SignWarp

permissions:
  signwarp.place.sign:
    default: op
    description: "Allow user to create warp"
  signwarp.touch.sign:
    default: true
    description: "Allow user to use warp"
  signwarp.cmd.xyz:
    default: true
    description: "Shows current x,y,z coordinates"
